import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
import {formatGBP,quarterRetailPence,isPurchasable} from '../src/lib/catalog.js';
const baseUrl = process.env.TEST_BASE_URL || 'http://localhost:5173';
fs.mkdirSync('.artifacts', { recursive: true });
const products=JSON.parse(fs.readFileSync('src/data/products.json','utf8'));
assert.equal(products.length,42);assert.equal(new Set(products.map(p=>p.id)).size,42);
assert.equal(quarterRetailPence(16999),4250);assert.equal(formatGBP(42.5),'£42.50');assert.equal(isPurchasable(undefined),false);
for(const p of products){if(!p.legacy)assert.equal(p.pricePence,quarterRetailPence(p.retailReference.retailPence));for(const img of p.images)assert.ok(fs.existsSync('public'+img));if(p.pricePence===null)assert.equal(isPurchasable(p),false);}
const browser=await chromium.launch({channel:'chrome',headless:true});
const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(baseUrl + '/products');await page.getByRole('heading',{name:'Explore the collection.'}).waitFor();
assert.equal(await page.locator('article.product-card').count(),42);
await page.getByRole('searchbox').fill('Porsche');assert.equal(await page.locator('article.product-card').count(),1);
await page.getByRole('link',{name:'View Product',exact:true}).click();
await page.getByRole('heading',{name:"LEGO Technic Porsche 911 RSR",exact:true}).waitFor();
assert.ok((await page.locator('main').innerText()).includes('£42.50'));
await page.getByRole('button',{name:'Add to Cart',exact:true}).click();
await page.goto(baseUrl + '/cart');assert.ok((await page.locator('main').innerText()).includes('£42.50'));
await page.reload();assert.ok((await page.locator('main').innerText()).includes("LEGO Technic Porsche 911 RSR"));
await page.goto(baseUrl + '/products/starter-bundle-best-seller');
assert.equal(await page.getByRole('button',{name:'Add to Cart',exact:true}).count(),0);
await page.getByRole('button',{name:'Enquire about this product'}).click();await page.waitForURL('**/contact');
await page.goto(baseUrl + '/products');await page.getByRole('combobox',{name:'Category'}).selectOption('Perfumes');assert.equal(await page.locator('article.product-card').count(),11);
await page.setViewportSize({width:420,height:844});await page.screenshot({path:'.artifacts/catalog-mobile.png',fullPage:false});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
await page.getByRole('searchbox').fill('nothing-matches');assert.equal(await page.locator('article.product-card').count(),0);
await page.goto(baseUrl + '/products/no-such-product');await page.getByRole('heading',{name:'Product not found'}).waitFor();
await page.setViewportSize({width:1280,height:900});await page.goto(baseUrl + '/');await page.getByRole('button',{name:/^products$/i}).first().click();await page.waitForURL('**/products');
await page.setViewportSize({width:1280,height:900});await page.locator('article.product-card').first().scrollIntoViewIfNeeded();await page.waitForTimeout(500);await page.screenshot({path:'.artifacts/catalog-desktop.png'});
assert.deepEqual(errors,[]);await browser.close();console.log('PASS: 42 listings, all image files, price rounding, search/filter, product/cart persistence, pending enquiry, missing route, mobile overflow, navigation; no page errors.');
