import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {getVariantPrice,isPurchasable,replaceCartVariant,quarterRetailPence} from '../src/lib/catalog.js';
const products=JSON.parse(fs.readFileSync('src/data/products.json','utf8'));const phone=products.find(p=>p.id==='iphone-18-pro-max');
assert.equal(phone.variants.length,16);assert.equal(getVariantPrice(phone,'Black / 2 TB'),385);assert.equal(isPurchasable(phone,'Blue / 2 TB'),false);
for(const p of products){assert.equal(p.variants.length,new Set(p.variants).size);assert.equal(p.variants.length,p.variantOptions.length);for(const v of p.variantOptions)if(!p.legacy)assert.equal(v.pricePence,quarterRetailPence(v.retailPence));}
const sample=[{id:'a',productId:phone.id,variant:'Black / 2 TB',quantity:2,optionNotes:'First request'},{id:'b',productId:phone.id,variant:'Silver / 512 GB',quantity:1,optionNotes:'Second request'}];
const merged=replaceCartVariant(sample,'a','Silver / 512 GB',products);assert.equal(merged.length,1);assert.equal(merged[0].quantity,3);assert.ok(merged[0].optionNotes.includes('First request'));assert.ok(merged[0].optionNotes.includes('Second request'));
const base=process.env.TEST_BASE_URL||'http://localhost:5173';const browser=await chromium.launch({channel:'chrome',headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
await page.goto(base+'/products/iphone-18-pro-max');await page.getByRole('combobox',{name:'Colour',exact:true}).selectOption('Black');await page.getByRole('combobox',{name:'Storage',exact:true}).selectOption('2 TB');assert.ok((await page.locator('main').innerText()).includes('£385.00'));
await page.getByRole('button',{name:'Add to Cart',exact:true}).click();await page.goto(base+'/checkout');
const aside=page.locator('aside');assert.equal(await aside.getByRole('combobox',{name:'Colour',exact:true}).inputValue(),'Black');
await aside.getByRole('combobox',{name:'Storage',exact:true}).selectOption('512 GB');await aside.getByRole('combobox',{name:'Colour',exact:true}).selectOption('Silver');
assert.ok((await aside.innerText()).includes('£345.00'));await aside.getByPlaceholder('Size, finish or bundle preferences').fill('Please confirm sealed box');
await page.reload();assert.equal(await aside.getByRole('combobox',{name:'Storage',exact:true}).inputValue(),'512 GB');assert.equal(await aside.getByRole('combobox',{name:'Colour',exact:true}).inputValue(),'Silver');assert.equal(await aside.getByPlaceholder('Size, finish or bundle preferences').inputValue(),'Please confirm sealed box');
await page.setViewportSize({width:420,height:844});await aside.scrollIntoViewIfNeeded();await page.screenshot({path:'.artifacts/checkout-options-mobile.png'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.goto(base+'/cart');await page.getByRole('button',{name:'Increase quantity',exact:true}).click();assert.ok((await page.locator('main').innerText()).includes('£690.00'));
await page.goto(base+'/products/phone-17-pro');await page.getByRole('combobox',{name:'Storage',exact:true}).selectOption('1 TB');assert.equal(await page.getByRole('button',{name:'Add to Cart',exact:true}).count(),1);
await page.goto(base+'/products/dnm-hoodie');await page.getByRole('combobox',{name:'Colour',exact:true}).selectOption('Grey');await page.getByRole('combobox',{name:'Size',exact:true}).selectOption('L');await page.getByRole('button',{name:'Add to Cart',exact:true}).click();await page.goto(base+'/checkout');assert.equal(await page.locator('aside').getByRole('combobox',{name:'Size',exact:true}).inputValue(),'L');
await page.getByRole('button',{name:/4\. Review/i}).click();await page.getByText('Silver / 512 GB', {exact:false}).first().waitFor();assert.ok((await page.locator('main').innerText()).includes('Please confirm sealed box'));
await page.getByRole('button',{name:/5\. Complete/i}).click();await page.getByRole('button',{name:/Telegram.*UK Telegram channel/i}).click();const summary=page.locator('pre').first();await summary.waitFor();assert.ok((await summary.innerText()).includes('Options: Silver / 512 GB'));assert.ok((await summary.innerText()).includes('Option requests: Please confirm sealed box'));assert.ok((await summary.innerText()).includes('Unit Price: £345.00'));
assert.deepEqual(errors,[]);console.log('PASS: 139 variant records; storage-specific price changes, checkout edits, notes and reload persistence, quantities, unknown-price protection, clothing options, mobile layout and merge behavior.');
}finally{await browser.close();}
